version: '3.8'

services:
  dy-downloader:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../Downloaded:/app/Downloaded
      - ../logs:/app/logs
      - ../settings:/app/settings
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 